package com.linbit.linstor.logging;

import com.linbit.linstor.core.LinStor;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Instant;
import java.time.temporal.ChronoUnit;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class LogArchiveTest
{
    // deliberately use a log-dir that is not used by any other test in order to avoid reading ErrorReports
    // that were generated by other unit tests.
    private static final String TEST_LOG_DIR = "build/test-logs/logarchive";

    private StdErrorReporter errReporter;

    // cleanup-method, doesn't matter if the dir existed and was deleted or didn't exist in the first place
    @SuppressFBWarnings("RV_RETURN_VALUE_IGNORED_BAD_PRACTICE")
    private void deleteDirectory(File directoryToBeDeleted)
    {
        File[] allContents = directoryToBeDeleted.listFiles();
        if (allContents != null)
        {
            for (File file : allContents)
            {
                deleteDirectory(file);
            }
        }
        directoryToBeDeleted.delete();

        Assert.assertFalse("Directory still exists", Files.exists(directoryToBeDeleted.toPath()));
    }

    @Before
    public void setUp()
    {
        deleteDirectory(Paths.get(TEST_LOG_DIR).toFile());
        errReporter = new StdErrorReporter(
            LinStor.SATELLITE_MODULE,
            Paths.get(TEST_LOG_DIR),
            false,
            "testnode",
            "INFO",
            "INFO"
        );
    }

    @After
    public void tearDown() throws Exception
    {
        errReporter.shutdown();
    }

    private Path createReportFile(String name) throws IOException
    {
        Path file = errReporter.getLogDirectory().resolve(name);
        Files.write(file, ("dummy content of " + name).getBytes(StandardCharsets.UTF_8));
        return file;
    }

    @Test
    public void testArchiveSkipsUnexpectedEntries() throws Exception
    {
        Path logDir = errReporter.getLogDirectory();

        Path report1 = createReportFile(StdErrorReporter.RPT_PREFIX + "ABCDEF01-00001-000001" +
            StdErrorReporter.RPT_SUFFIX);
        Path report2 = createReportFile(StdErrorReporter.RPT_PREFIX + "ABCDEF01-00001-000002" +
            StdErrorReporter.RPT_SUFFIX);

        // an unexpected non-empty directory whose name looks like an error-report, as seen in
        // https://forums.linbit.com/t/error-volume-group-name-not-found/1257 - Files.delete would
        // fail on it with a DirectoryNotEmptyException
        Path rogueDir = logDir.resolve(StdErrorReporter.RPT_PREFIX + "ABCDEF01-00001-000003" +
            StdErrorReporter.RPT_SUFFIX);
        Files.createDirectory(rogueDir);
        Path rogueDirContent = rogueDir.resolve("agent.4132");
        Files.write(rogueDirContent, "copied report content".getBytes(StandardCharsets.UTF_8));

        // an empty directory with a matching name must also be left alone
        Path emptyRogueDir = logDir.resolve(StdErrorReporter.RPT_PREFIX + "ABCDEF01-00001-000004" +
            StdErrorReporter.RPT_SUFFIX);
        Files.createDirectory(emptyRogueDir);

        // files not matching the error-report naming format must be left alone
        Path wrongSuffix = createReportFile(StdErrorReporter.RPT_PREFIX + "ABCDEF01-00001-000005.txt");
        Path wrongPrefix = createReportFile("SomeOtherFile-000006" + StdErrorReporter.RPT_SUFFIX);

        // cutoff in the future so that all just created entries are "old enough" to be archived
        errReporter.archiveLogsOlderThan(Instant.now().plus(1, ChronoUnit.DAYS));

        Assert.assertFalse("Error-report was not archived", Files.exists(report1));
        Assert.assertFalse("Error-report was not archived", Files.exists(report2));

        Assert.assertTrue("Unexpected directory was deleted", Files.isDirectory(rogueDir));
        Assert.assertTrue("Content of unexpected directory was deleted", Files.exists(rogueDirContent));
        Assert.assertTrue("Unexpected empty directory was deleted", Files.isDirectory(emptyRogueDir));
        Assert.assertTrue("File with unexpected suffix was deleted", Files.exists(wrongSuffix));
        Assert.assertTrue("File with unexpected prefix was deleted", Files.exists(wrongPrefix));

        boolean tarFound = false;
        try (DirectoryStream<Path> dirStream = Files.newDirectoryStream(logDir, "log-archive-*.tar.gz"))
        {
            for (Path tarFile : dirStream)
            {
                tarFound = true;
                Assert.assertTrue("Archive is empty", Files.size(tarFile) > 0);
            }
        }
        Assert.assertTrue("No archive was created", tarFound);
    }
}
