package com.linbit.linstor.core.apicallhandler.controller.db;

import com.linbit.linstor.core.ClassPathLoader;
import com.linbit.linstor.dbcp.migration.MigrationTestBase;
import com.linbit.linstor.dbdrivers.DatabaseTable;
import com.linbit.linstor.dbdrivers.DatabaseTable.SelfReferencingForeignKey;
import com.linbit.linstor.dbdrivers.GeneratedDatabaseTables;
import com.linbit.linstor.dbdrivers.k8s.crd.GenCrd;
import com.linbit.linstor.dbdrivers.k8s.crd.GenCrdCurrent;
import com.linbit.linstor.testutils.EmptyErrorReporter;

import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Safety net for the db export/import: the export does not guarantee any order of the entries within a
 * table, and the entries of a table are imported in the order the tables appear in the export (which is the
 * order of GeneratedDatabaseTables.ALL_TABLES at export time). Foreign keys therefore rely on the following
 * invariants:
 * <ul>
 * <li>GeneratedDatabaseTables.SELF_REFERENCING_FOREIGN_KEYS has to contain exactly the self-referencing
 * foreign keys of the latest schema version, so that {@link DbExportImportHelper} reorders the entries of
 * those tables during import. The constant is generated by GenerateSql, so a mismatch means that a migration
 * changed the self-referencing foreign keys without GenerateSql having been re-run.</li>
 * <li>GeneratedDatabaseTables.ALL_TABLES has to list a referenced table before all tables referencing
 * it.</li>
 * <li>Every versioned GenCrd* class has to provide the SELF_REFERENCING_FOREIGN_KEYS constant within its
 * nested GeneratedDatabaseTables copy, since the import looks up the constant of the export's schema
 * version.</li>
 * </ul>
 */
public class SelfReferencingTablesTest extends MigrationTestBase
{
    private record Fk(String referencedTbl, String referencedClm, String referencingTbl, String referencingClm)
    {
    }

    @Test
    public void selfReferencingFksConstantMatchesLatestSchema() throws Exception
    {
        List<SelfReferencingForeignKey> selfRefFksInSchema = new ArrayList<>();
        for (Fk fk : collectFksOfLatestSchema("selfRefFkCheck"))
        {
            if (fk.referencedTbl().equals(fk.referencingTbl()))
            {
                selfRefFksInSchema.add(
                    new SelfReferencingForeignKey(fk.referencingTbl(), fk.referencedClm(), fk.referencingClm())
                );
            }
        }

        assertThat(GeneratedDatabaseTables.SELF_REFERENCING_FOREIGN_KEYS)
            .as(
                "GeneratedDatabaseTables.SELF_REFERENCING_FOREIGN_KEYS must contain exactly the " +
                    "self-referencing foreign keys of the latest database schema, so that the db import " +
                    "reorders the entries of the affected tables. The constant is generated - re-run " +
                    "GenerateSql to update it."
            )
            .containsExactlyInAnyOrderElementsOf(selfRefFksInSchema);
    }

    @Test
    public void allTablesListsReferencedTablesFirst() throws Exception
    {
        Map<String, Integer> tblIdxMap = new HashMap<>();
        DatabaseTable[] allTables = GeneratedDatabaseTables.ALL_TABLES;
        for (int idx = 0; idx < allTables.length; idx++)
        {
            tblIdxMap.put(allTables[idx].getName(), idx);
        }

        for (Fk fk : collectFksOfLatestSchema("crossTblFkCheck"))
        {
            Integer referencedIdx = tblIdxMap.get(fk.referencedTbl());
            Integer referencingIdx = tblIdxMap.get(fk.referencingTbl());
            // tables that are not part of ALL_TABLES are not exported at all
            if (referencedIdx != null && referencingIdx != null &&
                !fk.referencedTbl().equals(fk.referencingTbl()))
            {
                assertThat(referencedIdx)
                    .as(
                        "The db export/import imports the entries of the tables in the order of " +
                            "GeneratedDatabaseTables.ALL_TABLES, which therefore must list %s before the " +
                            "table %s referencing it (foreign key %s -> %s.%s)",
                        fk.referencedTbl(),
                        fk.referencingTbl(),
                        fk.referencingClm(),
                        fk.referencedTbl(),
                        fk.referencedClm()
                    )
                    .isLessThan(referencingIdx);
            }
        }
    }

    /**
     * The import reads the SELF_REFERENCING_FOREIGN_KEYS constant of the GenCrd* class matching the export's
     * data version (through {@link DbExportPojoDataDeserializationHelper}). This test runs that exact lookup
     * for every versioned GenCrd* class to ensure none of them is missing the constant.
     */
    @Test
    public void allGenCrdVersionsProvideSelfReferencingFks() throws Exception
    {
        ClassPathLoader classPathLoader = new ClassPathLoader(new EmptyErrorReporter());
        List<Class<?>> genCrdClasses = classPathLoader.loadClasses(
            GenCrdCurrent.class.getPackage().getName(),
            Collections.singletonList(""),
            null,
            GenCrd.class
        );

        int checkedVersions = 0;
        for (Class<?> genCrdCls : genCrdClasses)
        {
            if (genCrdCls != GenCrdCurrent.class)
            {
                String dataVersion = genCrdCls.getAnnotation(GenCrd.class).dataVersion();
                SelfReferencingForeignKey[] selfRefFks = new DbExportPojoDataDeserializationHelper(
                    new EmptyErrorReporter(),
                    dataVersion
                )
                    .getSelfReferencingForeignKeys();
                assertThat(selfRefFks)
                    .as("SELF_REFERENCING_FOREIGN_KEYS of %s (data version %s)", genCrdCls.getSimpleName(), dataVersion)
                    .isNotNull();
                checkedVersions++;
            }
        }
        // paranoia check that the classpath scan actually found the versioned GenCrd* classes
        assertThat(checkedVersions).isGreaterThan(0);
    }

    /**
     * Migrates a fresh in-memory H2 database to the latest schema version and returns all of its foreign
     * keys (one entry per referencing column).
     */
    private List<Fk> collectFksOfLatestSchema(String dbName) throws Exception
    {
        startDbAtVersion(dbName, null); // null: migrate to the latest version

        List<Fk> fks = new ArrayList<>();
        DatabaseMetaData metaData = conn.getMetaData();
        try (ResultSet tblRs = metaData.getTables(null, null, "%", new String[] {"TABLE"}))
        {
            while (tblRs.next())
            {
                String tblName = tblRs.getString("TABLE_NAME");
                try (ResultSet fkRs = metaData.getImportedKeys(null, null, tblName))
                {
                    while (fkRs.next())
                    {
                        fks.add(
                            new Fk(
                                fkRs.getString("PKTABLE_NAME"),
                                fkRs.getString("PKCOLUMN_NAME"),
                                fkRs.getString("FKTABLE_NAME"),
                                fkRs.getString("FKCOLUMN_NAME")
                            )
                        );
                    }
                }
            }
        }
        return fks;
    }
}
