package com.linbit.linstor.layer.drbd.resfiles;

import com.linbit.ImplementationError;

import org.junit.Test;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

public class DrbdResourceFileUtilsTest
{
    private static final String HEADER_A = """
        # This file was generated by linstor(1.0), do not edit manually.
        # Generated at 2026-06-18 10:00:00
        """;
    private static final String HEADER_B = """
        # This file was generated by linstor(1.0), do not edit manually.
        # Generated at 2026-06-18 11:30:00
        """;
    private static final String RES_BODY = """
        resource "rsc"
        {
            net
            {
                cram-hmac-alg     sha1;
            }
        }
        """;
    private static final String OTHER_BODY = """
        resource "rsc"
        {
            net
            {
                cram-hmac-alg     sha256;
            }
        }
        """;

    @Test
    public void testEqualIgnoringHeader()
    {
        // Same resource section, different (timestamped) headers -> equal
        assertTrue(DrbdResourceFileUtils.isResFileEqual(HEADER_A + RES_BODY, HEADER_B + RES_BODY));
    }

    @Test
    public void testDifferentBody()
    {
        assertFalse(DrbdResourceFileUtils.isResFileEqual(HEADER_A + RES_BODY, HEADER_B + OTHER_BODY));
    }

    @Test
    public void testEmptyOnDiskContent()
    {
        // The regression: an existing but empty .res file must not throw, it must report "not equal"
        // so the caller rewrites the file.
        assertFalse(DrbdResourceFileUtils.isResFileEqual("", HEADER_B + RES_BODY));
    }

    @Test
    public void testCorruptOnDiskContent()
    {
        // On-disk content without a resource section (truncated / corrupt) -> not equal, force rewrite
        assertFalse(DrbdResourceFileUtils.isResFileEqual("# only a header, file got truncated\n", HEADER_B + RES_BODY));
    }

    @Test
    public void testGeneratedContentMissingResourceSectionThrows()
    {
        // The freshly generated content must always contain a resource section; if it does not,
        // that is a real implementation error and must still be reported.
        try
        {
            DrbdResourceFileUtils.isResFileEqual(HEADER_A + RES_BODY, "not a res file");
            fail("Expected ImplementationError when generated content has no resource section");
        }
        catch (ImplementationError expected)
        {
            // expected
        }
    }
}
